theme: jekyll-theme-cayman
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "fenced_code_blocks", "lax_spacing", "no_intra_emphasis", "space_after_headers", "strikethrough", "superscript", "tables"]